### ISSUE TITLE
Checking for Dev build Updates not working.

### ISSUE THREAD

**Issue by 5T33Z0** [ic005k/OCAuxiliaryTools#291]
I've noticed in the last couple of days that OCAT doesn't really download new builds any more when clicking on "Get OpenCore".

It says: "No Update available".

But when I download the latest dev build manually and import it, it's clear the latest version wasn't intsalled.

Could you look that?

Thanks.

**Comment by ic005k** [comment]
For the update source, if you choose

https://github.com/dortania/build-repo

you can view its distribution file here

https://github.com/dortania/build-repo/releases

OCAT cannot get the development version of OpenCore when the first file is not OpenCore.

In this case, you can choose another update source, which is always only for OpenCore, so there is no problem

https://github.com/bugprogrammer/HackinPlugins


Any questions or ideas, please feel free to leave a comment, thanks.

**Comment by ic005k** [comment]
Because the current online update source except the official one (which needs to be downloaded manually and then imported into OCAT). Other online update sources are not perfect, for example, they don't support Linux system. So OCAT will have to do for now, if there are any changes, I will always pay attention and upgrade OCAT at the first time.

**Comment by ic005k** [comment]
This issue has been optimized in the latest version, please upgrade to the latest version.
